import asyncio
import os
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from google import genai

# 1. Initialize the FastAPI app (Cloud Run needs a web server)
app = FastAPI(title="Event Marketing MAS Demo")

# 2. Initialize the Gemini Client
# It automatically picks up the GEMINI_API_KEY environment variable
try:
    client = genai.Client()
except Exception as e:
    client = None

# 3. Define our Data Models (The input and output structures)
class CampaignRequest(BaseModel):
    event_description: str

class CampaignResponse(BaseModel):
    copywriting: str
    engagement_strategy: str
    summary: str

# 4. Define Agent A: The Copywriter
async def run_copywriter_agent(description: str) -> str:
    prompt = f"""
    You are an expert tech event copywriter. 
    Based on this event description: "{description}"
    
    Draft:
    1. A short, engaging LinkedIn post (with emojis).
    2. A crisp Twitter/X thread (2 tweets).
    3. A brief email blast subject line and body.
    """
    # Run the Gemini call in a separate thread so it doesn't block our parallel workflow
    response = await asyncio.to_thread(
        client.models.generate_content,
        model='gemini-3-flash-preview',
        contents=prompt,
    )
    return response.text

# 5. Define Agent B: The Engagement Strategist
async def run_strategist_agent(description: str) -> str:
    prompt = f"""
    You are an event engagement strategist.
    Based on this event description: "{description}"
    
    Create:
    1. 3 interactive quiz questions to post leading up to the event.
    2. 2 visual poster themes for the design team.
    """
    response = await asyncio.to_thread(
        client.models.generate_content,
        model='gemini-2.5-flash',
        contents=prompt,
    )
    return response.text

# 6. Define The Root Agent: Campaign Director (The Orchestrator)
@app.post("/generate-campaign", response_model=CampaignResponse)
async def campaign_director(request: CampaignRequest):
    if not client:
        raise HTTPException(status_code=500, detail="Gemini client not initialized. Check GEMINI_API_KEY.")
        
    print(f"Director: Received request for -> {request.event_description}")
    print("Director: Delegating to Copywriter and Strategist in PARALLEL...")
    
    # Fire off both tasks at the same time
    copy_task = run_copywriter_agent(request.event_description)
    strategy_task = run_strategist_agent(request.event_description)
    
    # Wait for both agents to finish their jobs
    copy_result, strategy_result = await asyncio.gather(copy_task, strategy_task)
    
    print("Director: Received all deliverables. Returning final payload.")
    
    return CampaignResponse(
        copywriting=copy_result,
        engagement_strategy=strategy_result,
        summary="Campaign successfully generated by the parallel multi-agent team."
    )

# 7. A simple health check endpoint for Cloud Run
@app.get("/")
def health_check():
    return {"status": "Marketing Agents are standing by."}